services:
  - type: web
    name: tnt-sistem-web
    runtime: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn tnt_core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: tnt-sistem-db
          property: connectionString
      - key: TIME_ZONE
        value: "Europe/Istanbul"
      - key: LANGUAGE_CODE_DEFAULT
        value: "tr"
      - key: PYTHON_VERSION
        value: "3.12.2"

databases:
  - name: tnt-sistem-db
    plan: starter
